(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Init_FloresFigueroa_atlas_1", frames: [[175,741,98,142],[0,741,173,147],[0,0,384,739]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_3 = function() {
	this.initialize(ss["Init_FloresFigueroa_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["Init_FloresFigueroa_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["Init_FloresFigueroa_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_1();
	this.instance.setTransform(0,0,0.1464,0.1464);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,56.3,108.2), null);


(lib.head = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// pupils
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjlAoQgKgLAAgOQAAgPAKgJQALgKAOAAQAPAAALAKQAKAJAAAPQAAAOgKALQgLALgPAAQgOAAgLgLgAC0AJQgKgJAAgPQAAgOAKgKQALgLAOAAQAOAAAKALQALAKAAAOQAAAPgLAJQgKAKgOAAQgOAAgLgKg");
	this.shape.setTransform(2,-13.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AjlAWQgKgGAAgIQAAgIAKgEQALgGAOAAQAPAAALAGQAKAEAAAIQAAAIgKAGQgLAFgPAAQgOAAgLgFgAC0AFQgKgFAAgHQAAgIAKgFQALgGAOAAQAOAAAKAGQALAFAAAIQAAAHgLAFQgKAGgOgBQgOABgLgGg");
	this.shape_1.setTransform(2,-13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape}]},5).to({state:[{t:this.shape_1}]},3).to({state:[]},1).to({state:[{t:this.shape_1}]},5).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).wait(9));

	// eyes
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AkWBZQgegfAAgrQAAgqAegfQAfgeArAAQAsAAAfAeQAeAfAAAqQAAArgeAfQgfAegsAAQgrAAgfgegACMAxQgdgcAAgoQAAgpAdgdQAdgdApAAQApAAAdAdQAdAdAAApQAAAogdAcQgdAdgpABQgpgBgdgdg");
	this.shape_2.setTransform(1.4,-14.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AkWBAQgegWAAgfQAAgfAegWQAfgWArABQAsgBAfAWQAeAWAAAfQAAAfgeAWQgfAWgsAAQgrAAgfgWgACMAkQgdgWAAgcQAAgeAdgUQAdgVApAAQApAAAdAVQAdAUAAAeQAAAcgdAWQgdAUgpAAQgpAAgdgUg");
	this.shape_3.setTransform(1.4,-14.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AkWAiQgegLAAgRQAAgQAegLQAfgNArAAQAsAAAfANQAeALAAAQQAAARgeALQgfAMgsAAQgrAAgfgMgACMATQgdgLAAgPQAAgPAdgMQAdgLApAAQApAAAdALQAdAMAAAPQAAAPgdALQgdAMgpAAQgpAAgdgMg");
	this.shape_4.setTransform(1.4,-14.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AjOAbQgFABgFgCIgCAAQgEABgDgCIgFAAIgBAAQgFABgGgCIgEAAIgBAAIgEgBIAAAAIgEAAIgEgBIgBAAIgCAAIgBAAIAAgBIgCAAIgBAAIgBgBIgCAAIgCgBIgJgCIgGgCIgCAAIgEgBIgBgBIgHgDIgGgGIAAAAIgBgBIAAgBIAAgBIgBAAIAAAAIAAgBIAAgDIAAAAIAAgBIABgBIAAAAIABgBIAAAAIABgBIAAAAIACAAIABAAIAAABIABAAIABAAIAAABIAAABIABAAIAAABIAAAAIAAABIABAAIABABIAAABIABAAIABAAIABABIAAAAIAGADIAGACIABAAIABAAIAGACIAHACIACAAIACAAIAAABIABAAIACAAIAAAAIAAAAIABAAIACAAIAAABIAEAAIAAABIACAAIACAAIABAAIAAAAIAAABIAEAAIAAAAIAAAAIAFAAIACABQAFgBAEACIAGAAIAAAAIAJAAIABABIAJAAIAlAAIACgBIAFAAIAAAAIABAAIABAAIABAAIABAAIAAAAIABAAIABgBIABAAIAAAAIACAAIADgBIACgBIABAAIAAAAIABgBIABAAIACgCIACgBIACAAIADgBIAFgDIAAAAIABAAIACgBIACgCIABgBIABAAIAAgBIACAAIAAgBIABAAIABAAIAAAAIABAAIAAgBIAAAAIABAAIAAgBIABgBIABAAIAAAAIABgCIACgBIADgDIABAAIABgBIAAAAIABAAIABAAIABAAIABAAIABABIABAAIAAAAIABABIAAAAIAAABIAAADIAAABIAAAAIgBABIgBACIgCABIgBAAIgBAAIAAAAIAAABIgBAAIAAAAIgDADIgEADIgBAAIgBABIgBABIAAABIgDABIgEADIgBABIgBAAIgBAAIgBABIgCAAIgBABIgBAAIAAABIgDABIgBAAIAAABIgBAAIAAAAIgBABIgBAAIgBABIAAAAIgEABIgGACIgFABIgHAAIgEABIgqAAgADKALIgCgBIgEAAIgBAAIgFgBIgBAAIgDAAIAAAAIgKgBIgBAAIgDgBIgCAAIgCAAIgBAAIAAAAIgHgBIgCgBIgHgBIgGgCIgDgBIgBAAIgBAAIgBgBIgBAAIgCAAIAAAAIgEgBIgFgCIgBAAIAAgBIgBAAIgBAAIAAgBIgBAAIgCgCIgEgCIgBAAIAAgBIgBAAIAAAAIgBAAIgBgBIAAAAIAAgBIgBAAIgCgBIgBgBIgBgBIgBgBIgBgBIAAgBIgBAAIAAgCIABgBIAAAAIAAgBIACgCIAAAAIABAAIADAAIADACIABAAIABABIABAAIABABIAAAAIABABIAAAAIABAAIAAAAIAAABIABAAIABABIABAAIABABIAAAAIABAAIABABIABAAIAAAAIABABIAAABIABAAIABAAIABABIABABIACAAIAEABIABABIABAAIABAAIABABIABAAIABAAIAAAAIAHACIAGACIACAAIACABIAGABIACAAIACAAIACABIABAAIADAAIABAAIAAAAIADAAIABAAIAGABIAAAAIADAAIABAAIAFAAIABAAIAEAAIABABIABAAIAcAAIABgBIADAAIABAAIACAAIADAAIABAAIADgBIACAAIACgBIAEAAIAHgCIAIgEIABAAIABAAIAAAAIABgBIAFgCIAGgEIACAAIADgCIABAAIABgBIABgBIABAAIABAAIAAgBIABAAIAAAAIABgBIAAAAIABAAIAAgBIABAAIABgCIABAAIAAgBIABAAIAAgBIABAAIAAgBIABAAIABAAIAAAAIABAAIABAAIABABIAAAAIABABIABABIAAAAIAAABIAAADIAAAAIAAABIgBAAIAAAAIAAABIAAAAIgBABIAAABIgBAAIAAAAIgBABIAAAAIgBACIgBAAIgBABIgBAAIgEADIgIAEIgBAAIgBABIgCABIgDABIgBABIAAAAIgBAAIgCABIgBAAIgCABIgBAAIAAAAIgBABIgBAAIgCAAIgDACIAAAAIgDABIgCAAIgBABIgBAAIgCABIgDAAIgCAAIgBABIAAAAIgEAAIgFABIgCABIgEAAIAAABIgCAAIgRAAIgQAAg");
	this.shape_5.setTransform(1.875,-11.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2}]}).to({state:[{t:this.shape_3}]},5).to({state:[{t:this.shape_4}]},3).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_4}]},3).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_2}]},1).wait(9));

	// head
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("ABFCdIgUAAIgVAAIgQAAIgBAAIgCAAIgCAAIgCgBIgBAAIgBgBIgBAAIgBgBIgBgBIgBgBIgBAAIAAAAIgFgBIgJAAIgHAAIgIAAIgHgBIgBAAIgBgBIgCgBIgBgBIgBAAIgBgBIgEgBIgDAAIgEAAIgDAAIgCAAIgDAAIgCgBIgBAAIgCAAIgBAAIgCgBIgCgBIgBAAIgBgBIgBgBIgEgBIgDAAIgDgBIgEAAIgDAAIgCAAIgCAAIgCAAIgBgBIgBAAIgBAAIgCgBIgBgBIgBAAIgCgBIgBgBIAAAAIgBgBIgBAAIgBgBIgBAAIgBgBIgBgBIgBgBIAAgCIgBgBIAAgCIAAgBIAAgCIABgBIAAgCIACgBIABgBIABgBIABAAIABgBIABAAIABAAIACAAIABAAIACABIABABIACAAIABABIACABIABABIADAAIADAAIAGABIAFAAIAEAAIADABIABABIACAAIABABIACAAIAAABIABABIACABIAEAAIAEAAIAGAAIADABIAEAAIACABIABAAIACABIABAAIABABIACABIABABIABAAIABAAIACAAIAJAAIAIAAIAIAAIAFABIAEACIACABIABABIACAAIABABIASAAIAQAAIARAAIASABQALABAEgDIgBgCIgBgBIgBgBIgBgBIgBgBIgBgBIgBgBIgBgCIgBgBIAAgBIgBgBIgBgBIAAgCIgBgBIAAgBIAAgCIAAgBIgBgCIAAgBIAAgCIAAgBIgBgCIgBgBIgBgBIgBgBIgBgCIAAgBIAAgCIgBgBIAAgCIgBgBIgBgBIAAgBIgBgBIgBgBIgBgCIgBgBIgBgDIgBgDIgBgBIAAgCIgBgBIgBgBIgBgCIAAgBIgBgCIgBgBIAAgCIgBgBIgBgBIgBgCIgBgBIAAgCIgBgBIAAgCIgBgBIAAgCIgBgBIgCgCIgBgBIAAgCIgBgBIAAgCIgBgBIAAgBIAAgCIAAgCIgBgCIAAgBIAAAAIAAgBIgBgBIgBgCIAAgBIgBgBIAAgBIgCgCIAAgBIAAgCIgBgCIAAgBIgBgCIgDgHIgDgGIgDgGIgBgEIgBgFIgBgEIgCgDIgBgCIgBgDIgBgEIgBgDIgBgCIAAgCIAAgBIgBgCIgBgBIAAgBIgBgCIAAgBIgBgCIAAgCIAAgCIgBgCIAAgBIgBgCIAAgBIAAgCIgBgBIgBgBIgBgBIAAgCIgBgBIAAgDIAAgDIgBgEIAAgDIAAgEIgBgCIgBgBIgBgCIgBgBIgBgBIAAgBIgBgCIAAgCIgBgBIAAgCIgBgCIAAgCIAAgCIgBgBIgBgCIAAgBIgBgCIgBgIIAAgLIAAgKIAAgJIAAgJIAAgBIABgBIABgBIAAgBIABgBIABgBIABAAIABgBIABAAIACAAIACAAIABAAIABABIABAAIABABIABABIAAABIABABIABABIAAABIABABIAAACIAAAHIAAAJIAAAHIAAAHIAAAHIABADIABADIACADIAAAEIABADIABADIABABIACABIAAACIABACIABADIABAEIAAAFIABAEIAAADIAAACIABABIABACIABABIAAABIABABIAAACIABACIAAABIAAACIAAACIABABIAAACIAAABIABACIAAABIABACIAAACIABABIABACIAAABIAAACIABABIAAACIAAABIABACIAAABIACACIAAABIABACIABABIAAABIABACIAAABIAAACIAAABIABACIAAACIAAABIACADIABADIACADIACADIABADIABADIABABIABACIAAABIAAABIABACIAAABIABACIABABIAAACIABABIABACIABABIAAACIABABIAAACIAAABIAAACIABABIAAACIAAACIABACIABABIABABIABABIABACIAAABIABACIAAACIABABIABABIAAACIABABIABABIABACIAAABIABACIABABIAAABIABACIABABIABABIABACIAAABIABACIAAABIABACIAAABIABABIABABIABABIABABIAAACIABABIABACIAAACIABABIAAACIABABIABABIAAABIABABIAAACIABABIABACIAAABIABACIAAADIABADIAAABIABABIAAACIABABIABABIABABIABABIACABIABABIABABIAAACIABABIAAABIABACIAAABIABABIAAABIABABIABACIABABIABABIAAABIABABIAAABIAAACIAAABIAAACIAAACIgBABIAAACIgCABIgBABIgBABIgBABIgBAAIgBABIgBAAIgBABIgCAAIgTABIgTAAgAhOCLIAAAAIAAAAg");
	this.shape_6.setTransform(-0.9,-8.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0000FF").s().p("AnLHMQi+i/AAkNQAAkMC+i/QC/i+EMAAQENAAC/C+QC+C/AAEMQAAENi+C/Qi/C+kNAAQkMAAi/i+gAh4AeIgBABIgBAAIgBABIgBABIgCABIAAABIgBACIAAACIAAABIAAABIABACIAAABIABACIABABIABABIABAAIABABIABAAIABAAIAAAAIABABIACABIABABIABABIACAAIABABIABAAIABABIACAAIACAAIACAAIADAAIAEAAIADABIADAAIAEABIABABIABAAIABABIACABIACAAIABAAIACABIABAAIACAAIADAAIACAAIADAAIAEABIADAAIAEABIABABIABAAIABABIACABIABABIABAAIAHABIAIAAIAHAAIAJAAIAFAAIAAAAIABABIABAAIACABIABABIABABIABABIABAAIACABIABAAIACAAIABAAIAQAAIAVAAIAUAAIATAAIATgBIACAAIABgBIABgBIABAAIABgBIABgBIABgBIABAAIACgBIAAgCIABgBIAAgDIAAgCIAAgBIAAgBIAAgBIgBgBIAAgCIgBgBIgBgBIgBgBIgBgBIAAgBIgBgBIAAgBIgBgCIAAgCIgBgBIAAgBIgBgBIgBgBIgCgBIgBgBIgBgBIgBgCIgBgBIAAgBIgBgBIAAgBIgBgEIAAgCIgBgCIAAgBIgBgDIgBgBIAAgBIgBgBIAAgBIgBgBIgBgBIAAgCIgBgCIAAgBIgBgCIgBgBIAAgCIgBgBIgBAAIgBgBIgBgBIAAgCIgBgBIAAgBIgBgCIAAgCIgBgBIgBgBIgBgBIgBgCIAAgBIgBgCIgBgBIAAgCIgBgBIgBgBIgBgBIAAgCIgBgBIgBgCIAAgCIgBgBIAAgBIgBgCIgBgBIgBgCIgBgBIgBgBIAAgCIAAgCIgBgCIAAgBIAAgCIAAgBIgBgBIAAgCIgBgCIgBgBIgBgCIAAgBIgBgBIgBgCIAAgCIgBgBIAAgCIAAAAIgBgCIgBgBIgBgDIgBgDIgCgDIgCgEIgBgDIgCgDIAAgCIAAgBIgBgCIAAgBIAAgCIAAgCIgBgBIAAgCIgBgBIgBgBIAAgBIgCgCIAAgCIgBgBIAAgCIAAgBIgBgBIAAgCIAAgCIgBgBIgBgCIAAgBIgBgCIAAgCIgBgBIAAgCIAAgBIgBgBIAAgCIAAgCIAAgCIgBgBIAAgCIgBgBIAAgBIgBgCIgBgBIgBgCIAAgBIAAgDIgBgEIAAgFIgBgEIgBgDIgBgCIAAgCIgCgBIgBgCIgBgCIgBgEIAAgDIgCgDIgBgDIgBgEIAAgGIAAgHIAAgHIAAgJIAAgHIAAgCIgBgBIAAgCIgBgBIgBgBIAAgBIgBgBIgBAAIgBAAIgBgBIgBAAIgCAAIgBAAIgBAAIgBABIgBAAIgBAAIgBABIAAABIgBABIgBABIgBACIAAAJIAAAJIAAAKIAAALIACAIIABABIAAACIABABIABACIAAACIAAACIABABIAAACIABACIAAACIABACIAAAAIABACIAAABIABABIABACIABACIAAADIAAAEIABADIAAADIAAAEIABABIAAABIABABIABABIABABIAAADIAAABIABACIAAABIABACIAAACIAAACIABACIAAABIABABIAAABIABACIABACIAAABIAAABIABACIABAEIABADIABADIABADIACADIABADIABAGIABAEIADAGIADAHIADAHIABACIAAABIABABIAAACIAAACIACACIAAABIABABIAAABIABABIABABIAAABIAAABIAAABIABACIAAABIAAACIAAABIABACIAAACIABABIAAABIABACIACABIABACIAAACIABABIAAABIABACIAAABIABACIABACIABABIABABIAAABIABACIABABIAAACIABACIABABIABABIAAABIABABIABADIABACIABACIABABIABACIABABIAAABIABABIABABIAAABIABACIAAABIAAACIABACIABABIABABIABABIABABIAAABIAAADIAAABIABACIAAABIAAABIAAACIABABIAAACIABABIABAAIAAACIABABIABABIABACIABABIABABIABABIABABIABABIABABQgEAEgLgBIgSgBIgRAAIgQAAIgSAAIgBgBIgBgBIgBgBIgCgBIgEgBIgGgBIgIAAIgIAAIgJAAIgCAAIgBAAIgBAAIgBgBIgCgBIgBgBIgBgBIgCAAIgBgBIgCAAIgEgBIgDAAIgGAAIgEgBIgEAAIgCgBIgBAAIAAgBIgCAAIgBgBIgCAAIgBgBIgDgBIgEgBIgFAAIgGAAIgDAAIgDAAIgBgBIgCgBIgBgBIgCgBIgBAAIgCgBIgBAAIgCAAIgBAAIgBAAgAhXA4IAAAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6}]}).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65,-65,130,130);


(lib.button = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF33FF").s().p("AqAKBQkJkJAAl4QAAl3EJkJQEJkJF3AAQF4AAEJEJQEJEJAAF3QAAF4kJEJQkJEJl4AAQl3AAkJkJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.button, new cjs.Rectangle(-90.6,-90.6,181.2,181.2), null);


(lib.walking = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// head
	this.instance = new lib.head();
	this.instance.setTransform(-20,-69.95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:-74.95},0).wait(2).to({y:-71.7},0).wait(2).to({y:-74.7},0).wait(2));

	// Layer_1
	this.instance_1 = new lib.CachedBmp_2();
	this.instance_1.setTransform(-43.15,-36.8,0.5,0.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AiyEaQgFgCgEgEQgDgDgCgFIgEgBQgHgCgGgEQgFgDgEgGIgBgCIAAgCIgBgCIgBgWIAAgjIABgiIABgBIAAgCIABgCIABgCIAAgEIAAgGIAAgKIAAgMIABgCIABgCIAAgCIAAgCIABgCIAAgCIAAgCIAAgCIABgCIABgBIABgCIABgCIABgCIAEgEIABgCIAAgCIAAgCIAAgCIABgEIAAgEIACgEIAFgGQAFgHAHgDIAEgBIAFAAIAAgBIAGABIAogCIAEgBIAwgCIABAAIADgBIAFAAIAAgBIDMAAQAFAAAEACIAKABIAAgBIAAgCIgBgCIgBgCIAAgCIgBgCIgBgCIgCgCIgBgCIgBgCIAAgCIgBgCIAAgCIgBgCIgBgEIAAgCIgCgCIAAgCIgBgCIgBgCIgCgCIgBgCIgBgBIAAgBIAAgCIgCgCIAAgCIgBgCIAAgCIgBgCIgBgCIgBgCIgBgCIgBgCIgBgCIAAgCIgBgCIgBgCIAAgCIgCgCIAAgCIAAgCIgBgCIgBgCIgCgCIgCgCIAAgCIgCgCIAAgCIAAgCIgBgBIgBgDIAAgBIgBgCIgBgCIAAgCIgBgCIgBgCIgBgCIgCgCIgBgCIgBgCIAAgCIgBgCIgBgCIAAgCIgBgCIgCgEIgCgEIgCgEIgDgGIAAgCIgBgCIgBgCIAAgCIgBgCIgBgBIgBgCIgBgCIgBgCIAAgCIgBgCIgBgCIgBgCIgBgCIgBgCIgBgCIAAgCIgBgCIAAgCIgBgCIgBgCIgBgCIgBgCIgBgCIAAgCIgCgCIAAgCIgBgCIAAgCIgBgCIgBgCIAAgCIAAgCIAAgCIgBgCIgBgBIAAgCIAAgCIgCgCIgBgCIgBgCIgBgCIgBgCIAAgCIAAgCIgCgCIAAgCIgBgCIAAgCIAAgCIgBgCIAAgCIgBgCIAAgCIgBgCIgBgCIgBgCIgBgCIgBgCIAAgCIgBgCIgBgCIgBgCIAAgCIAAgBIgCgCIAAgCIgBgCIgBgCIgCgCIgBgCIgBgCIgBgCIgBgCIAAgCIgBgCIAAgCIgBgCIABgCIAAgCIAAgCIABgCIAAgCIABgCIADgEIAEgDIAGgEIAEgCIAFAAIAAgBIADABIAFAAIAEABIADACIAEACIADAEIACAEIAEAGIADAGIABACIAAACIABACIAAACIABACIABACIABACIABACIAAACIABACIABACIABACIABABIABACIABACIAAACIABACIAAACIABACIABACIAAACIAAACIAAACIACACIAAACIAAACIABACIACACIABACIABACIAAACIABACIAAACIABACIAAACIABACIAAACIAAACIABACIABACIAAACIAAACIABABIABADIABABIABACIABACIABACIABACIAAACIABACIABACIAAACIABACIABACIABACIABACIABACIAAACIAAACIACACIABACIABACIAAACIABACIABACIABACIAAACIABACIAAACIABACIABACIABABIABADIABABIABACIABACIAAACIADAEIACAEIACAEIADAGIABACIAAACIABACIABACIAAACIABACIABACIABACIABACIABACIABACIACAEIABACIAAABIABACIAAACIABACIABACIABACIABACIAAACIACACIAAACIACACIAAACIABACIAAACIABACIAAACIACAEIAAACIACACIABACIABACIABACIABACIABACIABAEIABAEIACACIACAGIAAACIACACIAAACIABACIABACIABACIABACIABACIAAACIABACIABACIABACIAAACIABACIABACIABACIAAACIABACIAAACIABACIABACIABACIAAACIABACIABACIAAABIABAEIABACIAAACIABACIABACIABACIAAACIAAACIAAABIABAAIAAACIABACIABACIAAACIAAACIAAACIAAACIgBACIgBACIAAACIgCACIgCAEIgCACIgCACIgDACIgEACIgCAAIgGABIgBAAQgHAAgHgDIgKgEIgWgHIgDgBIgKgBIgFgBIgDAAIgBgBIi9AAIgBAAQgZAFgagCIgEABQgPADgOAAIAAAXIAAAhIAAACIABACIABACIAAAcIABAnQAAASgCASIgCAEIgCADQgCAEgEACIgGAEIgCAAIgGABIgJgCg");
	this.shape.setTransform(-44.275,-8.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("ACeFkIhhgCIgJgBQglACgigMIgEgBIgFgCIgCgCIgEgEIgCgCIgBgCIgBgCIAAgCIgBgBIAAgCIAAgCIgBgCIABgCIAAgCIABgCIAAgCIAAgBIAAgNQAAgJABgJIABgGIABgCIAAgCIAAgCIAAgBIAAgCIABgEIAAgEIAAgCIABgCIABgCIAAgCIABgEIAAgEIABgCIAAgCIABgCIAAgGIABgIIACgLIAAgIIABgCIABgCIABgCIACgCIAAgCIAAgCIABgCIAAgCIABgCIABgCIAAgCIAAgCIABgCIABgEIABgEIACgGIABgEIABgCIABgCIABgCIAAgBIACgCIAAgCIAAgCIAAgCIABgCIAAgCIAAgCIABgEIAAgCIABgCIABgCIAAgCIAAgCIABgCIAAgCIABgCIABgCIAAgCIAAgEIAAgEIAAgFIAAgGIAAgCIABgCIAAgCIAAgCIAAgCIAAgCIAAgCIABgEIAAgEIABgCIAAgCIAAgIIAAgOIAAgGIgKgMQgHgIgFgIIgBgCIgBgCIgBgCIgBgCIgBgCIgCgBIgBgCIgBgCIAAgCIgCgCIgBgCIgBgCIgBgCIgCgEIgDgEIAAgCIgBgCIAAgCIgBgCIgBgCIgCgEIgDgDIgDgGIAAgCIgBgCIgGgKIgKgRIgOgVIgCgCIAAgBIgBgCIgFgJIgMgNIgMgQIgBgCQgFgDgDgFIgIgLIgLgOIAAgCIgCgCIgCgCIgCgCIgBgCIgBgCIgDgEIgCgEIgEgGIgGgIIgBgCIgDgEIgCgDIgEgGIgFgIIgBgCIgBgCIgBgCIgBgCIgCgCIgBgCIgCgEIgDgEIAAgCIgBgCIAAgCIgBgCIgCgCIgBgCIgBgCIgBgCIgCgEIgBgBIgBgCIgBgCIgBgCIgCgCIgBgCIgBgCQgEgDgCgFQgDgIgFgGIgNgQIgBgCIAAgCIAAgCIgBgBIAAgCIAAgCIAAgCIAAgCIABgCIABgCIAAgCIACgCIABgCIAEgEIAHgEIADgBIAGgBIAAAAIAEAAIAFABIAEABIADACIADACIAGAGIAHAKQAFAFADAGIACAGIAFAGIAFAIIAFAKIAEAIIABACIABACIAAACIANAVIAUAdIASAcIACACIACACIACACIABACIABACIABACIACACIABACIABACIABACIAVAXIAZAhIAQAZIAAACIABABIAEAGIAFAIIAFAKIAEAIIAAACIABACIABACIAAACIABACIACACIAAACIACACIAAACIABACIACAEIACADIADAGIAFAIIAAACIABACIABACIABACIABACIACACIAAACIACACIADACIACACIABACIABACIABACIAEADIAEAEIAFAGIAEAFIAAACIABACIAAACIAAACQACAIgBAJIgBAdQgBAPAAAPIgBACIgBACIAAACIAAAEIAAADIgBAIIgBAIIAAACIgBACIgBACIgBACIAAACIgBACIAAACIAAACIgBAEIAAACIgBACIAAACIgBACIAAACIAAACIgBACIgBACIgBACIAAACIAAABIgBACIgBACIgCACIAAACIgBACIAAACIgBACIAAACIgBACIAAACIAAACIgBACIAAACIgBACIgBACIAAACIAAACIgBACIAAACIgBACIgBACIgBACIgBACIAAACIAAACIAAACIAAACIgBADIAAACIgBACIAAACIAAACIAAACIAAACIAAACIgBAEIgBAEIgBACIAAACIAAACIAAACIAAACIgBAEIAAACIgCACIAAACIAAACIAAACIAAACIgBAEIAAAEIAAABIgBACIgBACIAAAGIAAACIAJACQAYgCAWAGIBoACIACAAQAagDAYAGIAEACIADACIACACIABACIADAEIAAACIACACIAAACIAAACIAAAEIAAACIAAAEIgCAEIgCAEQgCADgEADIgDACIgDABQgQADgQAAQgPAAgQgDg");
	this.shape_1.setTransform(19.225,0.6625);

	this.instance_2 = new lib.CachedBmp_3();
	this.instance_2.setTransform(-41.8,-37.45,0.5,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("ADKEPIgJgDQgFgCgDgEIgDgCIgFgCIgDgCIgEgCQgJgCgJgGIgUgMIgNgHQgHgBgHgFIgMgIIgKgHIgFgCIgHgFIgEgDIgBgBIgHgDIgGgGIgBgCIgBgCIgBgCIgBgCIAAgCIAAgCIAAgCIAAgCIAAgCIAAgCIAAgCIAAgCIABgBIABgCIACgCIACgCIABgCIACgCIADgCIAAAAIAFgFIAJgJIAGgEIAEgEIAIgGIACgCIACgCIADgCIADgCIABgCIAEgCIADgBIADgDIACgCIADgBQAFgCADgEIALgIIAJgIIADgCIACgCIADgCIACgCIABgCIAAAAIgCgDQgDgDgFgCIgCgCIgDgCIgEgCIgDgCIgDgCIgIgGIgNgIIgIgEIgEgEIgHgEIgGgEIgEgBIgHgEIgKgGIgHgEIgCgCIgDgCIgDgCIgCgBIgCgCIgEgCIgDgCIgBgBIgCgBIgCgCIgGgEIgHgEIgKgGQgQgOgSgNQgVgOgUgRIgJgFIgDgEIgEgDIgGgFIgDgCIgDgCIgBgCIgDgBIgFgDIgDgBIgFgEIgFgFIgFgDIgBgCIgCgCIgCgCIgDgCIgCgCIgDgCIgDgCIgGgGIgIgHQgHgGgFgHIgDgBIgDgDIgFgDIgEgEIgIgGIgGgEIgCgCIgCgCIgBgCIgCgCIgCgCIgGgGIgHgIIgJgMIgBgCIgBgCIAAgBIgBgCIgCgCIgBgCIgCgCIgBgCIgCgEIgBgCIgBgCIAAgCIgBgCIAAgCIAAgCIABgCIAAgCIABgCIABgCIABgCIABgCIABgCIACgCIACgCIAEgCIACgBIABgBIADAAIAFgBIACAAIAFABIAEABIAEACIADACIAEAEIADAEIACAEIAEAGIABACIAAACIACACIABABIACADIACABIABACIACACIACACIADACIACACIACACIABACIAEACIACACIABACIACACIADACIAEACIACACIABACIACACQAHADAEAFIAMALQAGAFAEAFIADACIADACIAEAEIACACIAFAEIADAEIAEACIADACIABACIAHAEIACACIAEACIADACIACACIACACIAEACIACACIACACIACACIADACIACACIABABIADADIAEABIABACIADACIAEACIADACIADACIAFAEIAHAEIAHAGIADACIADACIADACIACACIABACIAKAHIAOAKIAKAIIAEADIAEABIADACIACACIACACIAEACIACACIABAAIADACIADACIABACIAEACIADACIACACIACACIARAJIAIAEQAKAGAJAHIACABIAVAMIAZARIAEACIAGAGIAIAGIAEACIADACIACACIACACIABACIABACIABACIABACIABAEIAAAEIAAAGIAAAKIgBAEIgGALQgIAMgLAKIgMAMQgEACgEAEQgEAFgGACIgLAGIgHAGIgLAIIgHAGIgEAFIAMAIIANAFIAPAIIASALIALAGIADABIAEABIAHAEIAIAEIAHAEIACACIAGAEIAFAEIACAEIADAGIACACIAAACIAAACIAAACIAAACIAAACIAAACIAAACIgDADIgCAEIgDAEIgGAEIgCACIgDAAIgFABIgJgDg");
	this.shape_2.setTransform(-19.35,-10.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhQFRIgKgKQgDgCgBgDIgDgCIgDgCIgDgCIgDgCIgBgCIgKgBQgKgBgIgGIgEgEIgEgCIgDgCIgEgCIgIgGIgNgLIgIgLIgDgCIgFgDIgDgFIgEgFIAAgCIgBgCIgBgCIgBgCIgCgEIgBgCIgCgCIAAgCIgBgCIAAgCIAAgCIgBgCIABgCIAAgCIABgCIAAgCIABgCIABgCIABgCIABgCIABgBIAAgCIAAgCIABgCIAAgCIABgCIABgCIAEgEIAEgEIAGgDIAFgHIAKgOIAMgPIABgCIABgCIABgCIACgCIADgCIACgCIAAgCIABgCIABgCIACgBIACgCIACgCIABgCIABgCIABgCIACgCIACgCIADgCIABgCIACgCIAOgSIAUgcQAFgIAHgFQARgXASgUQAYgaAWgbQAEgGAHgFQAEgJAGgHQAJgNAJgNIAFgHIAAAAIAEACIADACIACACIADACIACACIADACIADACIAGAEIAKAGIAHAEIgDAEIgOAUIgWAgQgGAHgGAGIgKALIgQAVQgGAGgGAEQgFAJgGAIIgXAaIgLALIgBACIgBACIgBABIgBACIgCACIgCACQgBAEgCADIgGAGIgIAJIgCACQgKARgNAPQgSAVgPAWQgEAHgHAGIAAACIgBACIgDAEIAAABIABABIACACIADACIACACIACACIACACIABACIACACIADACIACACIAGAEIAIAEIAHAFIAEABIADACIADACIACACIABACIAEACIACACIADACIACACIAEACIABABIACABIAFABIACACIAEACIACACIABACIACACIABACIABACIACACIACACIABACIABACIABACIABACIAAACIABACIAAACIAAACIAAACIABACIgBACIAAACIAAACIAAACIgBACIAAACIgBABIgBACIgBACIgBACIgCACIgFAEIgFACIgEABIgFABQgHAAgGgEgAByh9IgRgJIgCgBIgDgDIgCgBIgEgCIgCgCIgDgCIgCgCIgBgBIACgDQADgHAFgGIACgCIAAgCIAAgCIACgCIAAgCIACgCIACgCIADgGIADgGIAGgKIACgEIABgCIAAgCIABgCIABgCIABgCIACgCIABgBIABgCIABgCIABgCIAAgCIABgCIABgCIABgCIABgCIABgCIABgCIABgCIABgCIADgEIABgCIABgCIAAgCIABgCIABgCIAAgCIAAgCIABgCIABgCIABgCIACgCIACgCIABgCIABgCIAAgBIABgCIAAgCIABgCIABgCIABgCIABgCIABgCIABgCIABgCIABgCIAAgCIAAgCIABgCIABgCIgBgCIAAgCIgBgCIAAgCIAAgCIAAgCIgBgCIABgCIAAgCIAAgCIAAgCIABgCIABgCIACgBIACgDIACgBIABgCIAEgCIADgCIADAAIAFgBIAAAAIACAAIAFABIAEABIADACIAEACIACACIABACIACACIABACIABACIAAACIACACIAAACIAAAGIABAFIAAAKIgBAKIgCACIgBACIAAACIgBACIAAACIgBACIAAACIgBACIAAACIgBACIgBACIgBACIgCACIAAACIAAACIgCACIAAABIgBACIgCAEIgBAEIgDAEIgDAGIgBACIgBACIAAACIgCACIAAACIgBACIgBACIgBACIgCACIgBAEIgBACIgBACIgDAGIgEAIIgHANIgDAGIgBACIgBACIgTAiIgKAQIgHgEg");
	this.shape_3.setTransform(-20.3,-1.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.shape_1},{t:this.shape}]},2).to({state:[{t:this.instance_2}]},2).to({state:[{t:this.shape_3},{t:this.shape_2}]},2).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85,-139.9,130,176.60000000000002);


(lib.rocket = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_25 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(25).call(this.frame_25).wait(1));

	// Layer_1
	this.instance = new lib.Symbol2();
	this.instance.setTransform(0,-0.05,1,1,0,0,0,28.1,54.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:-7.5},0).wait(1).to({y:-15},0).wait(1).to({y:-22.5},0).wait(1).to({y:-30},0).wait(1).to({y:-37.45},0).wait(1).to({y:-44.95},0).wait(1).to({y:-52.45},0).wait(1).to({y:-59.95},0).wait(1).to({y:-67.45},0).wait(1).to({y:-74.9},0).wait(1).to({y:-82.4},0).wait(1).to({y:-89.9},0).wait(1).to({y:-97.4},0).wait(1).to({y:-104.9},0).wait(1).to({y:-112.35},0).wait(1).to({y:-119.85},0).wait(1).to({y:-127.35},0).wait(1).to({y:-134.85},0).wait(1).to({y:-142.35},0).wait(1).to({y:-149.8},0).wait(1).to({y:-157.3},0).wait(1).to({y:-164.8},0).wait(1).to({y:-172.3},0).wait(1).to({y:-179.8},0).to({_off:true},1).wait(1));

	// fire
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF8C00").s().p("AiqCrQhGhHgBhkQABg1AUgtQASgnAgghQBHhGBjAAQBkAABGBGQAiAhARAnQAVAtgBA1QAABkhHBHQhGBGhkAAQhjAAhHhGgAhch9QgNANgJAOQgTAgAAAmQAAA5ApAoQAoApA5AAQA5AAApgpQAogoAAg5QAAgmgTggQgJgOgMgNQgpgpg5AAQg5AAgoApg");
	this.shape.setTransform(2.5,54.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgcASgXIAGgHQAYgYAiAAQAjAAAYAYIAGAHQASAXAAAcQAAAigYAZQgYAYgjAAQgiAAgYgYg");
	this.shape_1.setTransform(2.7,49.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFD700").s().p("AhhBiQgogoAAg6QAAgmASggQAJgOANgNQApgoA4AAQA6AAAoAoQANANAJAOQASAgABAmQAAA6gpAoQgoAog6AAQg4AAgpgogAg9hNIgFAHQgTAXABAeQAAAhAXAYQAZAZAjgBQAhABAYgZQAZgYgBghQABgegTgXIgGgHQgYgXghAAQgjAAgZAXg");
	this.shape_2.setTransform(2.95,51.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF8C00").s().p("AiqCrQhHhHAAhkQAAg0AVguQARgnAhghQBHhGBjAAQBkAABHBGQAgAhASAnQAVAuAAA0QgBBkhGBHQhHBHhkAAQhjAAhHhHgAhch9QgOANgIAOQgTAgAAAnQAAA4ApAoQAoApA4AAQA6AAAogpQApgoAAg4QAAgngSggQgKgOgNgNQgogpg6AAQg4AAgoApg");
	this.shape_3.setTransform(1.75,44.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgcASgXIAGgHQAYgYAiAAQAiAAAZAYIAGAHQASAXAAAcQAAAjgYAXQgZAZgiAAQgiAAgYgZg");
	this.shape_4.setTransform(1.95,40.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFD700").s().p("AhhBiQgogpAAg5QgBgmAUggQAIgOANgNQApgoA4AAQA6AAAoAoQANANAJAOQASAgAAAmQAAA5goApQgoAog6AAQg4AAgpgogAg9hNIgGAHQgSAXAAAdQAAAiAYAYQAZAZAjgBQAhABAYgZQAYgYABgiQgBgdgRgXIgHgHQgYgXghAAQgjAAgZAXg");
	this.shape_5.setTransform(2.2,41.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQAAg1AUgtQARgnAhghQBHhGBjAAQBkAABGBGQAhAhASAnQAVAtgBA1QABBkhIBHQhGBHhkAAQhjAAhHhHgAhdh9QgMAMgJAPQgTAfAAAoQAAA4AoAoQApApA5AAQA5AAApgpQAogoAAg4QAAgogTgfQgJgPgMgMQgpgpg5AAQg5AAgpApg");
	this.shape_6.setTransform(1.55,38.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgdASgWIAGgHQAYgYAiAAQAjAAAXAYIAHAHQASAWAAAdQAAAjgZAXQgXAZgjAAQgiAAgYgZg");
	this.shape_7.setTransform(1.75,34.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QAAgmATggQAJgOANgNQApgoA4AAQA5AAApAoQANANAJAOQASAgABAmQAAA5gpApQgpAog5AAQg4AAgpgogAg8hNIgHAHQgSAXABAdQAAAiAYAYQAYAZAigBQAiABAYgZQAYgYAAgiQAAgdgSgXIgGgHQgYgXgiAAQgiAAgYAXg");
	this.shape_8.setTransform(2,35.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQgBg1AVgtQASgnAgghQBHhHBjAAQBkAABHBHQAgAhASAnQAUAtAAA1QAABkhGBHQhHBGhkABQhjgBhHhGgAhdh9QgNAMgIAPQgTAgAAAnQAAA4AoApQApAoA4AAQA6AAAogoQApgpAAg4QAAgngTggQgIgPgOgMQgogpg6AAQg4AAgpApg");
	this.shape_9.setTransform(2.35,31);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag6A6QgYgYAAgiQAAgcASgXIAGgHQAZgYAhAAQAjAAAXAYIAHAHQASAXAAAcQAAAigZAYQgXAZgjAAQghAAgZgZg");
	this.shape_10.setTransform(2.55,26.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QABgmASggQAJgOANgNQApgoA4AAQA5AAApAoQANANAJAOQATAggBAmQABA6gpAoQgpApg5AAQg4AAgpgpgAg8hMIgHAGQgRAXgBAdQAAAiAZAYQAYAYAiAAQAiAAAYgYQAZgYAAgiQAAgdgSgXIgHgGQgYgYgiAAQgiAAgYAYg");
	this.shape_11.setTransform(2.8,28.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF8C00").s().p("AiqCqQhGhGgBhkQABg1AUgtQASgnAgghQBHhGBjAAQBkAABGBGQAiAhARAnQAVAtgBA1QAABkhHBGQhGBIhkgBQhjABhHhIgAhch+QgNANgJAPQgTAfAAAnQAAA5ApAoQAoApA5AAQA5AAApgpQAogoAAg5QAAgngTgfQgJgPgMgNQgpgog5AAQg5AAgoAog");
	this.shape_12.setTransform(1.6,25.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgdASgWIAGgHQAYgYAiAAQAjAAAYAYIAGAHQASAWAAAdQAAAigYAZQgYAYgjAAQgiAAgYgYg");
	this.shape_13.setTransform(1.8,20.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFD700").s().p("AhhBiQgogpAAg5QAAgmASgfQAJgPANgNQApgpA4AAQA6AAAoApQANANAJAPQASAfABAmQAAA5gpApQgoAog6AAQg4AAgpgogAg9hNIgFAIQgTAWABAeQAAAhAXAYQAZAYAiABQAigBAYgYQAZgYgBghQABgegTgWIgGgIQgYgYgiAAQgiAAgZAYg");
	this.shape_14.setTransform(2.05,22.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QABgmASgfQAJgPANgNQApgpA4AAQA5AAApApQANANAJAPQATAfAAAmQAAA5gpApQgpApg5AAQg4AAgpgpgAg8hMIgGAHQgSAWAAAdQAAAiAYAYQAYAZAiAAQAiAAAYgZQAYgYAAgiQABgdgTgWIgGgHQgYgZgiAAQgiAAgYAZg");
	this.shape_15.setTransform(1.7,12.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FF8C00").s().p("AiqCqQhGhGAAhkQAAg0AUguQARgnAhghQBHhHBjAAQBkAABGBHQAiAhARAnQAVAugBA0QABBkhIBGQhGBHhkAAQhjAAhHhHgAhdh+QgMAOgJAOQgTAfAAAnQAAA5AoApQApAoA5AAQA5AAApgoQAogpAAg5QAAgngTgfQgIgOgNgOQgpgog5AAQg5AAgpAog");
	this.shape_16.setTransform(1.25,15.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FF8C00").s().p("AiqCrQhHhHAAhkQAAg0AVguQAIgSALgQQANgUASgSQBHhHBjAAQBkAABHBHQASASANAUQALAQAIASQAUAuABA0QAABkhHBHQhHBHhkAAQhjAAhHhHgAhWiEIgHAHQgNANgIAOQgTAgAAAnQAAA4AoApQApAoA4AAQA6AAAogoQApgpAAg4QAAgngSggQgKgOgNgNIgHgHQgmgig1AAQgzAAgnAig");
	this.shape_17.setTransform(1.65,7.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgcASgXIAGgHQAZgYAhAAQAiAAAZAYIAGAHQASAXAAAcQAAAjgYAXQgZAZgiAAQghAAgZgZg");
	this.shape_18.setTransform(1.85,2.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QAAgmAUggQAIgOANgNIAHgGQAmgjA0ABQA1gBAmAjIAHAGQANANAJAOQASAgAAAmQAAA6goAoQgoApg6AAQg5AAgogpgAg9hMIgGAGQgSAXAAAdQAAAiAYAYQAZAYAjAAQAhAAAYgYQAYgYABgiQgBgdgRgXIgHgGQgYgYghAAQgjAAgZAYg");
	this.shape_19.setTransform(2.1,4.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQAAg0AUguQAIgRALgRQANgUASgSQBHhHBjAAQBkAABGBHQATASANAUQALARAIARQAUAuAAA0QABBkhIBHQhGBHhkAAQhjAAhHhHgAhViEIgIAHQgMANgJAOQgTAgAAAnQAAA4AoApQApAoA5AAQA5AAApgoQAogpAAg4QAAgngTggQgIgOgNgNIgIgHQgmgig0AAQg0AAgmAig");
	this.shape_20.setTransform(1.8,1.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgcASgXIAGgHQAYgYAiAAQAiAAAYAYIAHAHQASAXAAAcQAAAjgZAXQgYAZgiAAQgiAAgYgZg");
	this.shape_21.setTransform(2,-3.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QABgmASggQAJgOANgNIAHgGQAngjAzABQA0gBAnAjIAHAGQANANAJAOQATAgAAAmQAAA6gpAoQgpApg5AAQg4AAgpgpgAg8hMIgHAGQgRAXgBAdQAAAiAZAYQAYAYAiAAQAiAAAYgYQAYgYAAgiQABgdgTgXIgGgGQgYgYgiAAQgiAAgYAYg");
	this.shape_22.setTransform(2.25,-1.65);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF8C00").s().p("AiqCqQhGhGAAhkQgBg1AVgtQAIgSALgQQANgUASgSQBHhGBjgBQBkABBHBGQASASANAUQALAQAIASQAUAtABA1QAABkhHBGQhHBHhkAAQhjAAhHhHgAhWiEIgHAGQgNAOgIAOQgTAfAAAnQAAA5AoAoQApApA4AAQA6AAAogpQApgoAAg5QAAgngSgfQgKgOgNgOIgHgGQgmgig1AAQgzAAgnAig");
	this.shape_23.setTransform(1.55,-15.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgdASgWIAGgHQAZgYAhAAQAjAAAXAYIAHAHQASAWAAAdQAAAigZAZQgXAYgjAAQghAAgZgYg");
	this.shape_24.setTransform(1.75,-19.75);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QAAgmATgfQAJgPANgNIAHgHQAmgiA0AAQA0AAAnAiIAHAHQANANAJAPQASAfAAAmQAAA5goApQgpAog5AAQg5AAgogogAg8hNIgHAIQgRAWgBAeQAAAhAZAYQAYAYAiABQAigBAYgYQAZgYAAghQAAgegSgWIgHgIQgYgYgiAAQgiAAgYAYg");
	this.shape_25.setTransform(2,-17.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQAAg0AUguQAIgRALgRQANgUASgSQBHhHBjAAQBkAABGBHQATASANAUQALARAIARQAVAugBA0QABBkhIBHQhGBHhkAAQhjAAhHhHgAhViEIgIAHQgMANgJAOQgTAgAAAnQAAA4AoApQApAoA5AAQA5AAApgoQAogpAAg4QAAgngTggQgIgOgNgNIgIgHQgmgig0AAQg0AAgmAig");
	this.shape_26.setTransform(1.7,-21.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgcASgXIAGgHQAYgYAiAAQAjAAAXAYIAHAHQASAXAAAcQAAAjgZAXQgXAZgjAAQgiAAgYgZg");
	this.shape_27.setTransform(1.9,-26);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QABgmASggQAJgOANgNIAHgGQAngjAzABQA1gBAmAjIAHAGQANANAJAOQATAgAAAmQAAA6gpAoQgpApg5AAQg4AAgpgpgAg8hMIgGAGQgSAXAAAdQAAAiAYAYQAYAYAiAAQAiAAAYgYQAYgYAAgiQABgdgTgXIgGgGQgYgYgiAAQgiAAgYAYg");
	this.shape_28.setTransform(2.15,-24.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FF8C00").s().p("AiqCqQhGhGAAhkQAAg1AUgtQAIgSALgQQANgUASgSQBHhGBjAAQBkAABGBGQATASANAUQALAQAIASQAUAtAAA1QABBkhIBGQhGBIhkgBQhjABhHhIgAhViEIgIAGQgMANgJAPQgTAfAAAnQAAA5AoAoQApApA4AAQA6AAApgpQAogoAAg5QAAgngTgfQgIgPgNgNIgIgGQgmgig1AAQgzAAgmAig");
	this.shape_29.setTransform(1.35,-28.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgcASgXIAGgHQAYgYAiAAQAiAAAYAYIAHAHQASAXAAAcQAAAigZAZQgYAYgiAAQgiAAgYgYg");
	this.shape_30.setTransform(1.55,-33.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QABgmASggQAJgOANgNIAHgHQAnghAzgBQA0ABAnAhIAHAHQANANAJAOQATAgAAAmQAAA6gpAoQgpAog5AAQg4AAgpgogAg8hNIgHAHQgRAXgBAeQAAAhAZAYQAYAZAigBQAiABAYgZQAYgYAAghQABgegTgXIgGgHQgYgYgiABQgigBgYAYg");
	this.shape_31.setTransform(1.8,-31.65);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQgBg1AVgtQAIgRALgRQANgUASgSQBHhGBjAAQBkAABHBGQASASANAUQALARAIARQAUAtABA1QAABkhHBHQhHBGhkAAQhjAAhHhGgAhWiEIgHAHQgNANgIAOQgTAgAAAmQAAA5AoAoQApApA4AAQA6AAAogpQApgoAAg5QAAgmgSggQgKgOgNgNIgHgHQgmgig1AAQgzAAgnAig");
	this.shape_32.setTransform(2,-44.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgcASgXIAGgHQAZgYAhAAQAjAAAXAYIAHAHQASAXAAAcQAAAigZAZQgXAYgjAAQghAAgZgYg");
	this.shape_33.setTransform(2.2,-49.15);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFD700").s().p("AhhBiQgpgoAAg6QAAgmATggQAJgOANgNIAHgHQAmghA0AAQA0AAAnAhIAHAHQANANAJAOQASAgAAAmQAAA6goAoQgpAog5AAQg5AAgogogAg8hNIgHAHQgRAXgBAeQAAAhAZAYQAYAZAigBQAiABAYgZQAZgYAAghQAAgegSgXIgHgHQgYgXgiAAQgiAAgYAXg");
	this.shape_34.setTransform(2.45,-47.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FF8C00").s().p("AiqCrQhHhHAAhkQAAg0AVguQAIgRALgRQANgUASgSQBHhHBjAAQBkAABHBHQARASAOAUQALARAIARQAVAuAAA0QgBBkhGBHQhHBHhkAAQhjAAhHhHgAhWiEIgGAHQgOANgIAOQgTAgAAAnQAAA4ApApQAoAoA4AAQA6AAAogoQApgpAAg4QAAgngSggQgKgOgNgNIgGgHQgngig1AAQgzAAgnAig");
	this.shape_35.setTransform(1.75,-68.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFD700").s().p("AhhBiQgogoAAg6QgBgmAUggQAIgOANgNIAHgGQAngjAzABQA0gBAnAjIAHAGQANANAJAOQASAgAAAmQAAA6goAoQgoApg6AAQg4AAgpgpgAg9hMIgGAGQgSAXAAAdQAAAiAYAYQAZAYAjAAQAhAAAYgYQAYgYABgiQgBgdgRgXIgHgGQgYgYghAAQgjAAgZAYg");
	this.shape_36.setTransform(2.2,-70.95);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FF8C00").s().p("AiqCrQhHhHAAhkQAAg0AVguQAIgRALgRQANgUASgSQBHhGBjAAQBkAABHBGQARASAOAUQALARAIARQAUAuABA0QAABkhHBHQhHBHhkAAQhjAAhHhHgAhWiEIgHAHQgNANgIAOQgTAgAAAnQAAA4AoAoQApApA4AAQA6AAAogpQApgoAAg4QAAgngSggQgKgOgNgNIgHgHQgmgig1AAQgzAAgnAig");
	this.shape_37.setTransform(0.75,-73.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QAAgmAUggQAIgOANgNIAHgHQAmghA0AAQA1AAAmAhIAHAHQANANAJAOQASAgAAAmQAAA5goApQgoAog6AAQg5AAgogogAg9hNIgGAHQgSAXAAAdQAAAiAYAYQAZAZAjgBQAhABAYgZQAYgYABgiQgBgdgRgXIgHgHQgYgXghAAQgjAAgZAXg");
	this.shape_38.setTransform(1.2,-76.45);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgdASgWIAGgHQAYgYAiAAQAiAAAZAYIAGAHQASAWAAAdQAAAigYAZQgZAYgiAAQgiAAgYgYg");
	this.shape_39.setTransform(2.6,-86.35);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFD700").s().p("AhhBiQgogpAAg5QgBgmAUgfQAIgPANgNIAHgHQAmgiA0AAQA1AAAmAiIAHAHQANANAJAPQASAfABAmQAAA5gpApQgoAog6AAQg5AAgogogAg9hNIgFAIQgTAWABAeQAAAhAXAYQAZAYAjABQAhgBAYgYQAZgYgBghQAAgegSgWIgGgIQgYgYghAAQgjAAgZAYg");
	this.shape_40.setTransform(2.85,-84.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FF8C00").s().p("AiqCqQhHhGAAhkQABg1AUgtQAIgSALgQQANgUASgSQBHhGBjgBQBkABBGBGQASASAOAUQALAQAIASQAVAtgBA1QAABkhHBGQhGBHhkAAQhjAAhHhHgAhViEIgHAGQgNAOgJAOQgTAfAAAnQAAA5ApAoQAoApA5AAQA5AAApgpQAogoAAg5QAAgngTgfQgJgOgMgOIgHgGQgngig0AAQg0AAgmAig");
	this.shape_41.setTransform(2.4,-81.65);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FF8C00").s().p("AiqCqQhHhGAAhkQABg1AUgtQAIgSALgQQANgUASgSQBHhGBjAAQBkAABGBGQASASAOAUQALAQAIASQAVAtgBA1QAABkhHBGQhGBIhkgBQhjABhHhIgAhViEIgHAGQgNANgJAPQgTAfAAAnQAAA5ApAoQAoApA5AAQA5AAApgpQAogoAAg5QAAgngTgfQgJgPgMgNIgHgGQgngig0AAQg0AAgmAig");
	this.shape_42.setTransform(2.4,-94.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("Ag6A7QgYgZAAgiQAAgcASgXIAGgHQAYgYAiAAQAiAAAZAYIAGAHQASAXAAAcQAAAigYAZQgZAYgiAAQgiAAgYgYg");
	this.shape_43.setTransform(2.6,-99.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFD700").s().p("AhhBiQgogoAAg6QgBgmAUggQAIgOANgNIAHgHQAmghA0gBQA1ABAmAhIAHAHQANANAJAOQASAgABAmQAAA6gpAoQgoAog6AAQg5AAgogogAg9hNIgFAHQgTAXABAeQAAAhAXAYQAZAZAjgBQAhABAYgZQAZgYgBghQAAgegSgXIgGgHQgYgYghABQgjgBgZAYg");
	this.shape_44.setTransform(2.85,-97.35);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFD700").s().p("AhhBiQgogoAAg6QgBgmAUggQAIgOANgNIAHgHQAnghAzgBQA0ABAnAhIAHAHQANANAJAOQASAgAAAmQAAA6goAoQgoAog6AAQg4AAgpgogAg9hNIgGAHQgSAXAAAeQAAAhAYAYQAZAZAjgBQAhABAYgZQAYgYABghQgBgegRgXIgHgHQgYgYghABQgjgBgZAYg");
	this.shape_45.setTransform(2.65,-104.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FF8C00").s().p("AiqCqQhHhGAAhkQAAg1AVgtQAIgSALgQQANgUASgSQBHhGBjAAQBkAABHBGQARASAOAUQALAQAIASQAVAtAAA1QgBBkhGBGQhHBIhkgBQhjABhHhIgAhWiEIgGAGQgOANgIAPQgTAfAAAnQAAA5ApAoQAoApA4AAQA6AAAogpQApgoAAg5QAAgngSgfQgKgPgNgNIgGgGQgngig1AAQgzAAgnAig");
	this.shape_46.setTransform(2.2,-101.25);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QABgmASggQAJgOANgNIAHgHQAnghAzAAQA0AAAnAhIAHAHQANANAJAOQATAgAAAmQAAA5gpApQgpAog5AAQg4AAgpgogAg8hNIgHAHQgRAXgBAdQAAAiAZAYQAYAZAigBQAiABAYgZQAYgYAAgiQABgdgTgXIgGgHQgYgXgiAAQgiAAgYAXg");
	this.shape_47.setTransform(2.25,-110.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQAAg0AUguQAIgRALgRQANgUASgSQBHhGBjAAQBkAABGBGQATASANAUQALARAIARQAUAuAAA0QABBkhIBHQhGBHhkAAQhjAAhHhHgAhViEIgIAHQgMANgJAOQgTAgAAAnQAAA4AoAoQApApA5AAQA5AAApgpQAogoAAg4QAAgngTggQgIgOgNgNIgIgHQgmgig0AAQg0AAgmAig");
	this.shape_48.setTransform(1.8,-107.35);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FF8C00").s().p("AiqCrQhGhHAAhkQgBg0AVguQAIgRALgRQANgUASgSQBHhGBjAAQBkAABHBGQASASANAUQALARAIARQAUAuAAA0QAABkhGBHQhHBHhkAAQhjAAhHhHgAhWiEIgHAHQgNANgIAOQgTAgAAAnQAAA4AoAoQApApA4AAQA6AAApgpQAogoAAg4QAAgngTggQgIgOgNgNIgIgHQgmgig1AAQgzAAgnAig");
	this.shape_49.setTransform(0.55,-118.6);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("Ag6A6QgYgXAAgjQAAgcASgXIAGgHQAZgYAhAAQAjAAAXAYIAHAHQASAXAAAcQAAAjgZAXQgXAZgjAAQghAAgZgZg");
	this.shape_50.setTransform(0.75,-123.3);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFD700").s().p("AhhBiQgpgpAAg5QABgmASggQAJgOANgNIAHgHQAmghA0AAQA0AAAnAhIAHAHQANANAJAOQATAggBAmQAAA5goApQgpAog5AAQg4AAgpgogAg8hNIgHAHQgRAXgBAdQAAAiAZAYQAYAZAigBQAiABAYgZQAZgYAAgiQAAgdgSgXIgHgHQgYgXgiAAQgiAAgYAXg");
	this.shape_51.setTransform(1,-121.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_5},{t:this.shape_4,p:{y:40.05}},{t:this.shape_3}]},1).to({state:[{t:this.shape_8},{t:this.shape_7,p:{x:1.75,y:34.1}},{t:this.shape_6}]},1).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]},1).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_7,p:{x:1.45,y:10.75}}]},1).to({state:[{t:this.shape_19,p:{x:2.1,y:4.65}},{t:this.shape_18,p:{x:1.85,y:2.8}},{t:this.shape_17,p:{x:1.65,y:7.5}}]},1).to({state:[{t:this.shape_22},{t:this.shape_21,p:{y:-3.5}},{t:this.shape_20}]},1).to({state:[{t:this.shape_19,p:{x:2,y:-9.85}},{t:this.shape_18,p:{x:1.75,y:-11.7}},{t:this.shape_17,p:{x:1.55,y:-7}}]},1).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]},1).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29}]},1).to({state:[{t:this.shape_19,p:{x:2.25,y:-38.45}},{t:this.shape_18,p:{x:2,y:-40.3}},{t:this.shape_17,p:{x:1.8,y:-35.6}}]},1).to({state:[{t:this.shape_34},{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_19,p:{x:2.45,y:-53.85}},{t:this.shape_18,p:{x:2.2,y:-55.7}},{t:this.shape_17,p:{x:2,y:-51}}]},1).to({state:[{t:this.shape_19,p:{x:2.45,y:-62.5}},{t:this.shape_18,p:{x:2.2,y:-64.35}},{t:this.shape_17,p:{x:2,y:-59.65}}]},1).to({state:[{t:this.shape_36},{t:this.shape_4,p:{y:-72.8}},{t:this.shape_35}]},1).to({state:[{t:this.shape_38},{t:this.shape_18,p:{x:0.95,y:-78.3}},{t:this.shape_37}]},1).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39}]},1).to({state:[{t:this.shape_19,p:{x:1.8,y:-93.15}},{t:this.shape_18,p:{x:1.55,y:-95}},{t:this.shape_17,p:{x:1.35,y:-90.3}}]},1).to({state:[{t:this.shape_44},{t:this.shape_43,p:{x:2.6,y:-99.2}},{t:this.shape_42}]},1).to({state:[{t:this.shape_46},{t:this.shape_45},{t:this.shape_43,p:{x:2.4,y:-105.95}}]},1).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_21,p:{y:-112.05}}]},1).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49}]},1).to({state:[]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.1,-233.9,56.3,312.6);


(lib.background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// rocket
	this.rocket_mc = new lib.rocket();
	this.rocket_mc.name = "rocket_mc";
	this.rocket_mc.setTransform(129.05,-473.85,3.4146,3.4146,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.rocket_mc).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("EAAABUYMAAAiovMEsAAAAMAAACovMksAAAAMkr/AAAMAAAiovMEr/AAA");
	this.shape.setTransform(0,-540);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFACA3","#0026DE"],[0,1],-960,0,959.9,0).s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_1.setTransform(2880,-540);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF2A12","#00AFCF"],[0,1],-960,0,959.9,0).s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_2.setTransform(960,-540);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FFFFFF","#000000"],[0,1],-960,0,959.9,0).s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape_3.setTransform(-960,-540);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.background, new cjs.Rectangle(-1921,-1081,5761,1082), null);


// stage content:
(lib.Init_FloresFigueroa = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		document.addEventListener("keydown", handleKeyDown);
		document.addEventListener("keyup", handleKeyUp);
		
		var root = this;
		var speed = 100; // speed
		
		function handleKeyDown(event) {
			console.log("scaleX:", root.blueHead_mc.scaleX);
			console.log("Background X:", root.background_mc.x); // Check this while testing
		
			// Only switch to "walking" if not already walking
			if (root.blueHead_mc.currentLabel !== "walking") {
				root.blueHead_mc.gotoAndPlay("walking");
			}
		
			// Expanded bounds for background movement
			// ➡️ RIGHT ARROW — background moves left
			if (event.keyCode == 39 && root.background_mc.x > -1000) {
				root.background_mc.x -= speed;
				root.blueHead_mc.scaleX = 1;
			}
		
			// ⬅️ LEFT ARROW — background moves right
			if (event.keyCode == 37 && root.background_mc.x < 2000) {
				root.background_mc.x += speed;
				root.blueHead_mc.scaleX = -1;
			}
		}
		
		function handleKeyUp(event) {
			if (event.keyCode == 37 || event.keyCode == 39) {
				root.blueHead_mc.gotoAndStop("standing");
			}
		}
		
		// ✅ Clickable rocket — plays animation once
		this.background_mc.rocket_mc.addEventListener("click", handleClickRocket);
		
		function handleClickRocket(event) {
			console.log("🚀 Rocket launched!");
			var whoosh_snd = createjs.Sound.play("whoosh");
			root.background_mc.rocket_mc.gotoAndPlay(1);
		
			// Prevent further clicks
			root.background_mc.rocket_mc.removeEventListener("click", handleClickRocket);
		}
		
		// ▶️ Play button — plays music and timeline
		this.play_btn.addEventListener("click", handleClickPlayButton);
		
		function handleClickPlayButton(event) {
			var music_snd = createjs.Sound.play("music");
			root.play();
		}
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// text
	this.text = new cjs.Text("Welcome to this test", "100px 'Nasalization'");
	this.text.textAlign = "center";
	this.text.lineHeight = 121;
	this.text.lineWidth = 1265;
	this.text.parent = this;
	this.text.setTransform(914.5,231.9);

	this.timeline.addTween(cjs.Tween.get(this.text).to({_off:true},1).wait(1));

	// button
	this.play_btn = new lib.button();
	this.play_btn.name = "play_btn";
	this.play_btn.setTransform(1650.25,878.25);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AOKAAQAAF3kKEJQkJEKl3AAQl2AAkKkKQkJkJAAl3QAAl2EJkKQEKkJF2AAQF3AAEJEJQEKEKAAF2g");
	this.shape.setTransform(1650.25,878.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.play_btn}]}).to({state:[]},1).wait(1));

	// walking
	this.blueHead_mc = new lib.walking();
	this.blueHead_mc.name = "blueHead_mc";
	this.blueHead_mc.setTransform(822.1,615.55,1,1,0,0,0,-20,-49.1);
	this.blueHead_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.blueHead_mc).wait(1).to({_off:false},0).wait(1));

	// background
	this.background_mc = new lib.background();
	this.background_mc.name = "background_mc";
	this.background_mc.setTransform(960,540,1,1,0,0,0,960,-540);
	this.background_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.background_mc).wait(1).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-960.5,539.5,4800.5,541);
// library properties:
lib.properties = {
	id: '979230AF9DB3A742BE37E526A3ADAD5F',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Init_FloresFigueroa_atlas_1.png?1744684691974", id:"Init_FloresFigueroa_atlas_1"},
		{src:"sounds/music.mp3?1744684692003", id:"music"},
		{src:"sounds/whoosh.mp3?1744684692003", id:"whoosh"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['979230AF9DB3A742BE37E526A3ADAD5F'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;